require('mappings')

require('settings')
require('settings.sys')
require('settings.auto')

require('plugins')
require('plugins.config.repeat')
require('plugins.config.airline')
require('plugins.config.bufonly')
require('plugins.config.supertab')
require('plugins.config.nvimtree')
require('plugins.config.ultisnipps')
require('plugins.config.floatterm')
require('plugins.config.telescope')
require('plugins.config.indentline')
require('plugins.config.autoformat')
require('plugins.custom.sandbox')

require('color-schemes')
require('color-schemes.gruvbox')
