-- require("nvim-lsp-installer").setup({
--     -- automatically detect which servers to install
--     -- (based on which servers are set up via lspconfig)
--     automatic_installation = true,
--     ui = {
--         icons = {
--             server_installed = "",
--             server_pending = "",
--             server_uninstalled = ""
--         }
--     }
-- })

--
--
--local lspconfig = require("lspconfig")
--local function on_attach(client, bufnr)
--    -- set up buffer keymaps, etc.
--end

--lspconfig.sumneko_lua.setup { on_attach = on_attach }

-- Setup nvim-cmp.
-- local cmp = require'cmp'

-- cmp.setup({
--     mapping = cmp.mapping.preset.insert({
--         ['<C-b>'] = cmp.mapping.scroll_docs(-4),
--         ['<C-f>'] = cmp.mapping.scroll_docs(4),
--         ['<C-Space>'] = cmp.mapping.complete(),
--         ['<C-e>'] = cmp.mapping.abort(),
--         ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
--     }),
--     sources = cmp.config.sources({
--         { name = 'nvim_lsp' },
--         -- { name = 'ultisnips' }, -- For ultisnips users.
--     }, {
--         { name = 'buffer' },
--     })
-- })
--
-- -- Set configuration for specific filetype.
-- cmp.setup.filetype('gitcommit', {
--     sources = cmp.config.sources({
--         { name = 'cmp_git' }, -- You can specify the `cmp_git` source if you were installed it.
--     }, {
--         { name = 'buffer' },
--     })
-- })
--
-- -- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
-- cmp.setup.cmdline('/', {
--     mapping = cmp.mapping.preset.cmdline(),
--     sources = {
--         { name = 'buffer' }
--     }
-- })
--
-- -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
-- cmp.setup.cmdline(':', {
--     mapping = cmp.mapping.preset.cmdline(),
--     sources = cmp.config.sources({
--         { name = 'path' }
--     }, {
--         { name = 'cmdline' }
--     })
-- })
--
-- -- Setup lspconfig.
-- local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
-- require('lspconfig')['<sumneko_lua>'].setup {
--     capabilities = capabilities
-- }
