# line width 
line_width: 120

# spaces to tab for indent
tab_size: 2

# separate flow control names from their parentheses with a space
separate_ctrl_name_with_space: false

# separate function names from parentheses with a space
separate_fn_name_with_space: false

# dangle the closing parenthesis on its own line.
dangle_parens: False

# If an argument group contains more than this many sub-groups (parg or kwarg) then force it to a vertical layout.
max_subgroups_hwrap: 2

# If a positional argument group contains more than this many arguments, then force it to a vertical layout.
max_pargs_hwrap: 2
